// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/access-policies": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access-policies"
                ],
                "summary": "List access policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controlplane.accessPolicyDTO"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access-policies"
                ],
                "summary": "Create an access policy",
                "parameters": [
                    {
                        "description": "Access policy",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controlplane.accessPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controlplane.accessPolicyDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            }
        },
        "/access-policies/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access-policies"
                ],
                "summary": "Get an access policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controlplane.accessPolicyDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Creates it if absent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access-policies"
                ],
                "summary": "Replace an access policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Access policy",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controlplane.accessPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controlplane.accessPolicyDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access-policies"
                ],
                "summary": "Delete an access policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            }
        },
        "/filter-policies": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filter-policies"
                ],
                "summary": "List filter policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controlplane.filterPolicyDTO"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filter-policies"
                ],
                "summary": "Create a filter policy",
                "parameters": [
                    {
                        "description": "Filter policy",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controlplane.filterPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controlplane.filterPolicyDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            }
        },
        "/filter-policies/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filter-policies"
                ],
                "summary": "Get a filter policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controlplane.filterPolicyDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Creates it if absent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filter-policies"
                ],
                "summary": "Replace a filter policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Filter policy",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controlplane.filterPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controlplane.filterPolicyDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filter-policies"
                ],
                "summary": "Delete a filter policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Control-plane health check",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mcps": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mcps"
                ],
                "summary": "List registered MCPs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controlplane.mcpRegistrationDTO"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Connects to the MCP, discovers its tools, and makes it immediately callable via the data plane. Persisted only on success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mcps"
                ],
                "summary": "Register an MCP",
                "parameters": [
                    {
                        "description": "MCP registration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controlplane.registerMCPRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controlplane.mcpRegistrationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            }
        },
        "/mcps/{name}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mcps"
                ],
                "summary": "Unregister an MCP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MCP name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controlplane.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controlplane.accessPolicyDTO": {
            "type": "object",
            "properties": {
                "grants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controlplane.grantDTO"
                    }
                },
                "match": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controlplane.claimRuleDTO"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controlplane.accessPolicyRequest": {
            "type": "object",
            "properties": {
                "grants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controlplane.grantDTO"
                    }
                },
                "match": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controlplane.claimRuleDTO"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controlplane.claimRuleDTO": {
            "type": "object",
            "required": [
                "path",
                "pattern"
            ],
            "properties": {
                "path": {
                    "type": "string"
                },
                "pattern": {
                    "type": "string"
                }
            }
        },
        "controlplane.connectConfigDTO": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "controlplane.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controlplane.filterPolicyDTO": {
            "type": "object",
            "properties": {
                "drop_fields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "match": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controlplane.claimRuleDTO"
                    }
                },
                "mcp": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tool": {
                    "type": "string"
                }
            }
        },
        "controlplane.filterPolicyRequest": {
            "type": "object",
            "required": [
                "mcp",
                "tool"
            ],
            "properties": {
                "drop_fields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "match": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controlplane.claimRuleDTO"
                    }
                },
                "mcp": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tool": {
                    "type": "string"
                }
            }
        },
        "controlplane.grantDTO": {
            "type": "object",
            "required": [
                "mcp"
            ],
            "properties": {
                "mcp": {
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controlplane.mcpRegistrationDTO": {
            "type": "object",
            "properties": {
                "connect": {
                    "$ref": "#/definitions/controlplane.connectConfigDTO"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tools": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/controlplane.toolSchemaDTO"
                    }
                },
                "transport": {
                    "type": "string"
                }
            }
        },
        "controlplane.registerMCPRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "connect": {
                    "$ref": "#/definitions/controlplane.connectConfigDTO"
                },
                "name": {
                    "type": "string"
                },
                "transport": {
                    "type": "string"
                }
            }
        },
        "controlplane.toolSchemaDTO": {
            "type": "object",
            "properties": {
                "input_schema": {
                    "type": "object"
                },
                "name": {
                    "type": "string"
                },
                "output_schema": {
                    "type": "object"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/admin",
	Schemes:          []string{},
	Title:            "MCP Gateway Control-Plane Admin API",
	Description:      "Admin API for registering downstream MCPs and managing access/filter policies. See ADR-0005 and ADR-0007.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
